name: Build and Push Frontend Docker Image

# Controls when the workflow will run
on:
    # Triggers the workflow on push events but only for the main branch
    push:
        branches:
            - main
        paths-ignore:
            - ".github/**"
            - "README.md"
    # Run manually
    workflow_dispatch:

jobs:
    build-and-push-frontend:
        runs-on: ubuntu-latest

        # Grant GITHUB_TOKEN permissions to write packages
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            # Set up Docker Buildx for multi-platform builds
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # Login to the container registry (GitHub Container Registry)
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Extract metadata (tags, labels) for Docker
            - name: Extract Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/${{ github.repository }}
                  tags: |
                      type=sha,prefix=
                      type=raw,value=latest,enable={{is_default_branch}}

            - name: Clean up disk space before build
              run: |
                  docker system prune -af || true
                  sudo rm -rf /usr/share/dotnet || true
                  sudo rm -rf /usr/local/lib/android || true
                  sudo rm -rf /opt/ghc || true
                  sudo rm -rf /tmp/* || true
                  sudo apt-get clean

            # Build and push the Docker image
            - name: Build and push Frontend Docker image
              uses: docker/build-push-action@v5
              with:
                  context: . # Build context is the root of the frontend repository
                  file: ./Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  build-args: |
                      VITE_API_BASE_BUILD_ARG=http://backend:8000
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
