name: Frontend licenses bundle

on:
  workflow_dispatch:

jobs:
  licenses:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: "npm"


    - name: Generate NOTICE + legal texts
      run: |
        npm ci --omit=dev
        rm -rf licenses
        mkdir  licenses
        npx license-checker-rseidelsohn --production \
          --markdown \
          --out licenses/NOTICE-frontend.md
        curl -L \
          "https://raw.githubusercontent.com/nodejs/node/v22.x/LICENSE" \
          -o licenses/NodeJS_LICENSE.txt
        curl -L \
          "https://raw.githubusercontent.com/nginx/nginx/master/LICENSE" \
          -o licenses/NGINX_LICENSE.txt

    - name: Upload licenses folder
      uses: actions/upload-artifact@v4
      with:
        name: licenses-frontend
        path: licenses
